import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleSource=fs.readFileSync(new URL('../src/modules/abastecimiento/AbastecimientoModule.jsx',import.meta.url),'utf8');
const service=fs.readFileSync(new URL('../src/services/abastecimientoSupabase.js',import.meta.url),'utf8');
const stock=fs.readFileSync(new URL('../src/services/stockService.js',import.meta.url),'utf8');
const vite=fs.readFileSync(new URL('../vite.config.js',import.meta.url),'utf8');
test('lecturas de Abastecimiento son Supabase-first',()=>{assert.match(service,/requireSupabase\(\)\.rpc\("abastecimiento_snapshot"/);assert.match(service,/requireSupabase\(\)\.rpc\("app_stock_snapshot"/);assert.match(moduleSource,/getAbastecimientoSnapshot/);assert.match(stock,/getStockSnapshotFromSupabase/);});
test('escrituras destructivas no exponen service role ni anon write',()=>{assert.doesNotMatch(service,/service_role|SUPABASE_SERVICE/);assert.match(service,/postBackend/);assert.match(service,/authToken|dm_auth_token/);});
test('se eliminó el transform Vite temporal de Abastecimiento',()=>{assert.doesNotMatch(vite,/abastecimientoInstantVitePlugin/);assert.equal(fs.existsSync(new URL('../scripts/abastecimiento-instant-vite-plugin.mjs',import.meta.url)),false);});
test('RABA03, remitos, estados e importación pasan por servicio unificado',()=>{for(const name of ['saveAbastecimientoRemito','deleteAbastecimientoRemito','setAbastecimientoEstado','appendAbastecimientoRaba03','updateAbastecimientoRaba03'])assert.match(moduleSource,new RegExp(name));});
