export const USER_AREA_OPTIONS=[
  "",
  "OFICINA TÉCNICA",
  "MANTENIMIENTO",
  "CALIDAD",
  "ABASTECIMIENTO",
  "TALLER CENTRAL",
  "LICITACIONES",
  "FINANZAS",
  "RECURSOS HUMANOS",
  "HIGIENE Y SEGURIDAD",
  "ADMINISTRATIVO",
  "SUPERVISOR",
  "GERENTE"
];
