export const USER_AREA_OPTIONS=[
  "",
  "OFICINA TECNICA",
  "CALIDAD",
  "RECURSOS HUMANOS",
  "HIGIENE Y SEGURIDAD",
  "FINANZAS",
  "GERENTE",
  "MECANICO",
  "ABASTECIMIENTO",
  "MANTENIMIENTO",
  "ADMINISTRATIVO EN SITIO",
  "SUPERVISOR EN SITIO"
];
