export const VIEW_REQUIRED_AREA = Object.freeze({
  dashboard: "OFICINA TÉCNICA",
  rop02: "OFICINA TÉCNICA",
  horometros: "OFICINA TÉCNICA",
  vehiculos: "OFICINA TÉCNICA",
  combustible: "OFICINA TÉCNICA",
  cambiosTurno: "OFICINA TÉCNICA",
  controlROP02: "OFICINA TÉCNICA",
  controlErrores: "OFICINA TÉCNICA",
  ctrlEquipo: "OFICINA TÉCNICA",
  atrasoROP02: "OFICINA TÉCNICA",
  rop05: "OFICINA TÉCNICA",
  rop05Discriminacion: "OFICINA TÉCNICA",
  ranking: "OFICINA TÉCNICA",
  chc: "OFICINA TÉCNICA",
  control: "OFICINA TÉCNICA",
  mant: "MANTENIMIENTO",
  distMant: "MANTENIMIENTO",
  pmProgramado: "MANTENIMIENTO",
  rma15CtrlEquipo: "MANTENIMIENTO",
  costosMant: "MANTENIMIENTO",
  costosUnitarios: "MANTENIMIENTO",
  listaEquipos: "TALLER CENTRAL",
  tallerCentral: "TALLER CENTRAL",
  abastecimiento: "ABASTECIMIENTO",
  abastecimientoDashboard: "ABASTECIMIENTO",
  abastecimientoPendientes: "ABASTECIMIENTO",
  abastecimientoParciales: "ABASTECIMIENTO",
  abastecimientoCerradas: "ABASTECIMIENTO",
  abastecimientoRechazadas: "ABASTECIMIENTO",
  abastecimientoRemito: "ABASTECIMIENTO",
  abastecimientoStock: "ABASTECIMIENTO",
  abastecimientoStockDashboard: "ABASTECIMIENTO",
  abastecimientoRABA03: "ABASTECIMIENTO",
  abastecimientoEditarCodigos: "ABASTECIMIENTO",
  licitaciones: "LICITACIONES",
  licitacionesNueva: "LICITACIONES",
  licitacionesControl: "LICITACIONES",
  licitacionesEquipos: "LICITACIONES",
  licitacionesDatosEquipos: "LICITACIONES"
});

export function getRequiredAreaForView(view) {
  return VIEW_REQUIRED_AREA[view] || "";
}
