import React,{useEffect,useRef,useState}from"react";
import ReactDOM from"react-dom";
import{updateAuthenticatedUser}from"../services/authSession.js";
import{USER_AREA_OPTIONS}from"../constants/userProfile.js";
import{APPEARANCE_ACCENTS,APPEARANCE_BACKGROUNDS,DEFAULT_APPEARANCE,fileToBackgroundDataUrl,loadCentralAppearance,normalizeAppearance,readLocalAppearance,saveCentralAppearance,writeLocalAppearance}from"../services/userAppearance.js";

const fieldStyle=C=>({background:C.surface,border:`1px solid ${C.border}`,borderRadius:9,padding:"11px 12px",color:C.text,outline:"none",width:"100%"});
const tabStyle=(C,active)=>({border:"none",borderBottom:`2px solid ${active?C.accent:"transparent"}`,background:active?C.accentDim:"transparent",color:active?C.accent:C.textSub,padding:"10px 14px",fontWeight:900,fontSize:11,cursor:"pointer"});

export default function UserSettingsModal({open,forced=false,onClose,onSaved,onAppearancePreview,APPS_SCRIPT_URL,C,Spinner,Icon,permissionSnapshot={}}){
 const email=String(sessionStorage.getItem("dm_user")||"");
 const[nombre,setNombre]=useState(()=>String(sessionStorage.getItem("dm_name")||""));const[area,setArea]=useState(()=>String(sessionStorage.getItem("dm_area")||""));
 const[actual,setActual]=useState("");const[nueva,setNueva]=useState("");const[repetir,setRepetir]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const[tab,setTab]=useState(forced?"security":"profile");const[appearance,setAppearance]=useState(()=>readLocalAppearance(email));const originalAppearance=useRef(appearance);const fileRef=useRef(null);
 const userRole=String(sessionStorage.getItem("dm_role")||"USUARIO").trim().toUpperCase();const canChangeArea=userRole==="ADMIN"||userRole==="ADMINISTRADOR";
 useEffect(()=>{if(!open)return;setNombre(String(sessionStorage.getItem("dm_name")||""));setArea(String(sessionStorage.getItem("dm_area")||""));setActual("");setNueva("");setRepetir("");setError("");setNotice("");setTab(forced?"security":"profile");const local=readLocalAppearance(email);setAppearance(local);originalAppearance.current=local;onAppearancePreview?.(local);if(!forced)loadCentralAppearance(APPS_SCRIPT_URL,email).then(p=>{setAppearance(p);originalAppearance.current=p;writeLocalAppearance(email,p);onAppearancePreview?.(p);}).catch(()=>{});},[open,forced,email,APPS_SCRIPT_URL]);
 if(!open)return null;
 const preview=next=>{const p=normalizeAppearance(next);setAppearance(p);onAppearancePreview?.(p);};
 const cancel=()=>{onAppearancePreview?.(originalAppearance.current);onClose?.();};
 const chooseImage=async e=>{try{const data=await fileToBackgroundDataUrl(e.target.files?.[0]);if(data)preview({...appearance,background:"custom",backgroundCustom:data});}catch(err){setError(err.message);}finally{if(e.target)e.target.value="";}};
 const guardar=async()=>{setError("");setNotice("");if(!nombre.trim()){setError("Ingresá un nombre.");setTab("profile");return;}if(forced&&!actual){setError("Ingresá la contraseña actual DELTA.MINING.APP.");return;}if(forced&&!nueva){setError("Elegí una nueva contraseña.");return;}if(nueva&&nueva.length<4){setError("La nueva contraseña debe tener al menos 4 caracteres.");return;}if(nueva!==repetir){setError("Las nuevas contraseñas no coinciden.");return;}if(nueva&&!actual){setError("Ingresá la contraseña actual.");return;}setSaving(true);try{const payload={action:"update_user_profile",email,currentPassword:actual,newPassword:nueva,nombre:nombre.trim(),area};const res=await fetch(APPS_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams({payload:JSON.stringify(payload)})});const json=await res.json();if(!json?.ok)throw new Error(json?.error?.message||"No se pudo guardar la configuración.");sessionStorage.setItem("dm_name",json.user?.nombre||nombre.trim());sessionStorage.setItem("dm_area",json.user?.area||area);updateAuthenticatedUser({nombre:json.user?.nombre||nombre.trim(),area:json.user?.area||area});sessionStorage.setItem("dm_must_change_password","0");const saved=writeLocalAppearance(email,appearance);let central=true;try{await saveCentralAppearance(APPS_SCRIPT_URL,email,saved);}catch(_){central=false;}originalAppearance.current=saved;onAppearancePreview?.(saved);if(!central)setNotice("Apariencia guardada en este equipo. La sincronización entre PCs quedará activa cuando se publique el endpoint de preferencias del backend.");onSaved?.({...json.user,appearance:saved,appearanceCentral:central});}catch(err){setError(err.message||"No se pudo guardar la configuración.");}finally{setSaving(false);}};
 const section=<>{tab==="profile"&&<div style={{display:"grid",gap:14}}><label style={{display:"grid",gap:6,fontSize:11,color:C.textSub,fontWeight:700}}>NOMBRE<input value={nombre} onChange={e=>setNombre(e.target.value)} style={fieldStyle(C)}/></label><label style={{display:"grid",gap:6,fontSize:11,color:C.textSub,fontWeight:700}}>ÁREA<select value={area} disabled={!canChangeArea} onChange={e=>setArea(e.target.value)} style={{...fieldStyle(C),opacity:canChangeArea?1:.65,cursor:canChangeArea?"pointer":"not-allowed"}}>{USER_AREA_OPTIONS.map(x=><option key={x} value={x}>{x||"SIN DEFINIR"}</option>)}</select>{!canChangeArea&&<span style={{fontSize:10,color:C.textMuted,fontWeight:500}}>El área la administra un usuario ADMIN.</span>}</label><div style={{height:1,background:`${C.border}66`}}/><div style={{display:"grid",gap:7}}><div style={{fontSize:11,color:C.textSub,fontWeight:800}}>PERMISOS EFECTIVOS</div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:6}}>{Object.entries(permissionSnapshot||{}).map(([areaName,actions])=><div key={areaName} style={{padding:"7px 8px",borderRadius:7,border:`1px solid ${C.border}66`,background:"rgba(255,255,255,.025)"}}><div style={{fontSize:9,fontWeight:800,color:C.text}}>{areaName}</div><div style={{fontSize:9,color:C.textMuted,marginTop:3}}>{(actions||[]).join(" · ")||"solo lectura"}</div></div>)}</div></div></div>}
 {tab==="appearance"&&<div style={{display:"grid",gap:16}}><div><div style={{fontSize:11,fontWeight:900,color:C.textSub,marginBottom:9}}>COLOR DE ÉNFASIS</div><div style={{display:"flex",gap:9,flexWrap:"wrap"}}>{APPEARANCE_ACCENTS.map(x=><button key={x.id} title={x.label} onClick={()=>preview({...appearance,accent:x.id})} style={{width:34,height:34,borderRadius:10,background:x.hex,border:appearance.accent===x.id?"3px solid #fff":"2px solid rgba(255,255,255,.15)",boxShadow:appearance.accent===x.id?`0 0 0 2px ${x.hex}`:"none",cursor:"pointer"}}/>)}</div><div style={{fontSize:10,color:C.textMuted,marginTop:7}}>Errores, advertencias y estados mantienen sus colores operativos.</div></div>
 <div><div style={{fontSize:11,fontWeight:900,color:C.textSub,marginBottom:9}}>IMAGEN DE FONDO</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:8}}>{APPEARANCE_BACKGROUNDS.map(x=><button key={x.id} onClick={()=>preview({...appearance,background:x.id})} style={{height:74,borderRadius:10,border:`2px solid ${appearance.background===x.id?C.accent:C.border}`,background:x.src?`linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.3)),url(${x.src}) center/cover`:C.bg,color:C.text,fontWeight:800,fontSize:10,cursor:"pointer"}}>{x.label}</button>)}</div><input ref={fileRef} type="file" accept="image/*" onChange={chooseImage} style={{display:"none"}}/><button onClick={()=>fileRef.current?.click()} style={{marginTop:8,width:"100%",padding:"9px 12px",borderRadius:9,border:`1px dashed ${appearance.background==="custom"?C.accent:C.border}`,background:"rgba(255,255,255,.025)",color:appearance.background==="custom"?C.accent:C.textSub,fontWeight:800,cursor:"pointer"}}>+ Subir mi imagen</button></div>
 <Range C={C} label="OSCURECIMIENTO DEL FONDO" value={appearance.backgroundDim} min={0} max={85} suffix="%" onChange={v=>preview({...appearance,backgroundDim:v})}/><Range C={C} label="DESENFOQUE DEL FONDO" value={appearance.backgroundBlur} min={0} max={16} suffix=" px" onChange={v=>preview({...appearance,backgroundBlur:v})}/><Range C={C} label="TRANSPARENCIA DE PANELES" value={appearance.panelOpacity} min={35} max={100} suffix="%" onChange={v=>preview({...appearance,panelOpacity:v})}/>
 <Choice C={C} label="DENSIDAD DE TABLAS" value={appearance.density} onChange={v=>preview({...appearance,density:v})} options={[["compact","Compacta"],["normal","Normal"],["comfortable","Cómoda"]]}/><Choice C={C} label="TAMAÑO DE INTERFAZ" value={appearance.scale} onChange={v=>preview({...appearance,scale:v})} options={[["small","Pequeña"],["normal","Normal"],["large","Grande"]]}/><Choice C={C} label="SIDEBAR AL INICIAR" value={appearance.sidebar} onChange={v=>preview({...appearance,sidebar:v})} options={[["remember","Recordar"],["expanded","Expandida"],["compact","Compacta"]]}/><label style={{display:"flex",alignItems:"center",gap:9,color:C.textSub,fontSize:11,fontWeight:800}}><input type="checkbox" checked={appearance.reducedMotion} onChange={e=>preview({...appearance,reducedMotion:e.target.checked})}/> Reducir animaciones</label><button onClick={()=>preview(DEFAULT_APPEARANCE)} style={{padding:"9px 12px",borderRadius:9,border:`1px solid ${C.border}`,background:C.surface,color:C.textSub,fontWeight:800,cursor:"pointer"}}>Restablecer apariencia predeterminada</button></div>}
 {tab==="security"&&<div style={{display:"grid",gap:14}}><label style={{display:"grid",gap:6,fontSize:11,color:C.textSub,fontWeight:700}}>CONTRASEÑA ACTUAL<input type="password" value={actual} onChange={e=>setActual(e.target.value)} placeholder={forced?"DELTA.MINING.APP":"Solo es necesaria para cambiar la contraseña"} style={fieldStyle(C)}/></label><label style={{display:"grid",gap:6,fontSize:11,color:C.textSub,fontWeight:700}}>NUEVA CONTRASEÑA<input type="password" value={nueva} onChange={e=>setNueva(e.target.value)} placeholder={forced?"Elegí tu nueva contraseña":"Dejar vacío para mantener la actual"} style={fieldStyle(C)}/></label><label style={{display:"grid",gap:6,fontSize:11,color:C.textSub,fontWeight:700}}>REPETIR NUEVA CONTRASEÑA<input type="password" value={repetir} onChange={e=>setRepetir(e.target.value)} style={fieldStyle(C)}/></label></div>}</>;
 return ReactDOM.createPortal(<div style={{position:"fixed",inset:0,zIndex:2147483646,background:"rgba(0,0,0,.74)",backdropFilter:"blur(6px)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{width:`min(${tab==="appearance"?"700px":"520px"},calc(100vw - 32px))`,maxHeight:"calc(100dvh - 32px)",background:"rgba(22,22,22,.98)",border:`1px solid ${forced?C.accent:C.border}`,borderRadius:16,boxShadow:"0 24px 80px rgba(0,0,0,.65)",overflow:"auto"}}><div style={{padding:"17px 20px 0",borderBottom:`1px solid ${C.border}66`}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",paddingBottom:12}}><div><div style={{fontSize:16,fontWeight:900,color:C.text}}>{forced?"Crear contraseña personal":"Configuración de usuario"}</div><div style={{fontSize:11,color:C.textMuted,marginTop:3}}>{forced?"Por seguridad, debe cambiar la contraseña inicial para continuar.":email}</div></div>{!forced&&<button onClick={cancel} style={{background:"none",border:"none",color:C.textMuted,fontSize:22,cursor:"pointer"}}>×</button>}</div>{!forced&&<div style={{display:"flex",gap:2}}><button style={tabStyle(C,tab==="profile")} onClick={()=>setTab("profile")}>Perfil</button><button style={tabStyle(C,tab==="appearance")} onClick={()=>setTab("appearance")}>Apariencia</button><button style={tabStyle(C,tab==="security")} onClick={()=>setTab("security")}>Seguridad</button></div>}</div><div style={{padding:20}}>{section}{error&&<div style={{marginTop:14,padding:"10px 12px",borderRadius:9,background:`${C.red}18`,border:`1px solid ${C.red}55`,color:C.red,fontSize:12,fontWeight:700}}>{error}</div>}{notice&&<div style={{marginTop:14,padding:"10px 12px",borderRadius:9,background:`${C.yellow}18`,border:`1px solid ${C.yellow}55`,color:C.yellow,fontSize:11,fontWeight:700}}>{notice}</div>}</div><div style={{padding:"0 20px 20px",display:"flex",justifyContent:"flex-end",gap:10}}>{!forced&&<button onClick={cancel} disabled={saving} style={{padding:"10px 16px",borderRadius:9,border:`1px solid ${C.border}`,background:C.surface,color:C.textSub,fontWeight:800,cursor:"pointer"}}>Cancelar</button>}<button onClick={guardar} disabled={saving} style={{padding:"10px 18px",borderRadius:9,border:`1px solid ${C.accent}88`,background:C.accentDim,color:C.accent,fontWeight:900,cursor:saving?"wait":"pointer",display:"flex",alignItems:"center",gap:7}}>{saving?<Spinner size={13}/>:<Icon name="check" size={14} color={C.accent}/>} {saving?"Guardando...":"Guardar cambios"}</button></div></div></div>,document.body);
}
function Range({C,label,value,min,max,suffix,onChange}){return <label style={{display:"grid",gap:7,fontSize:11,color:C.textSub,fontWeight:800}}><span style={{display:"flex",justifyContent:"space-between"}}><span>{label}</span><b style={{color:C.text}}>{value}{suffix}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} style={{accentColor:C.accent}}/></label>}
function Choice({C,label,value,onChange,options}){return <div style={{display:"grid",gap:7}}><div style={{fontSize:11,color:C.textSub,fontWeight:800}}>{label}</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{options.map(([id,text])=><button key={id} onClick={()=>onChange(id)} style={{padding:"8px 11px",borderRadius:8,border:`1px solid ${value===id?C.accent:C.border}`,background:value===id?C.accentDim:C.surface,color:value===id?C.accent:C.textSub,fontSize:10,fontWeight:800,cursor:"pointer"}}>{text}</button>)}</div></div>}
