from pathlib import Path

p=Path('src/modules/abastecimiento/AbastecimientoModule.jsx')
s=p.read_text(encoding='utf-8')

old='''  const confirmRejectSolicitud=useCallback(async()=>{\n    const row=rejectModal.row;\n    if(!row)return;\n    const observacion=String(rejectModal.observacion||\"\").trim();\n    if(!observacion){\n      appAlert(\"Ingresá una observación para rechazar la solicitud.\");\n      return;\n    }\n    const key=buildSolicitudKey(row);\n    setActionLoading(\"Guardando rechazo en Google Sheets...\");\n    try{\n      await postEstadoSolicitud(\"save_estado_solicitud\",{estado:{\n        clave:key,estado:\"RECHAZADA\",observacion,\n        nSolicitud:row.nSolicitud||\"\",codigoArticulo:row.codigoArticulo||\"\",\n        descripcion:row.descripcion||\"\",fechaSolicitud:row.fechaSolicitud||\"\",usuario:sessionStorage.getItem(\"dm_user\")||\"APP\"\n      }});\n      await loadEstadosSolicitudesCompartidos({silent:true});\n      setRejectModal({open:false,row:null,observacion:\"\"});\n    }catch(err){appAlert(\"No se pudo guardar el rechazo para todos: \"+(err?.message||err));}\n    finally{setActionLoading(\"\");}\n  },[rejectModal,buildSolicitudKey,postEstadoSolicitud,loadEstadosSolicitudesCompartidos]);\n'''
new='''  const confirmRejectSolicitud=useCallback(async()=>{\n    const row=rejectModal.row;\n    if(!row)return;\n    const observacion=String(rejectModal.observacion||\"\").trim();\n    if(!observacion){\n      appAlert(\"Ingresá una observación para rechazar la solicitud.\");\n      return;\n    }\n    const key=buildSolicitudKey(row);\n    const info={\n      observacion,\n      nSolicitud:row.nSolicitud||\"\",\n      codigoArticulo:row.codigoArticulo||\"\",\n      descripcion:row.descripcion||\"\",\n      fecha:row.fechaSolicitud||\"\",\n      usuario:sessionStorage.getItem(\"dm_user\")||\"APP\"\n    };\n    setActionLoading(\"Guardando rechazo en Google Sheets...\");\n    try{\n      // Esta es la única espera necesaria para confirmar que Google Sheets escribió.\n      await postEstadoSolicitud(\"save_estado_solicitud\",{estado:{\n        clave:key,estado:\"RECHAZADA\",observacion,\n        nSolicitud:info.nSolicitud,codigoArticulo:info.codigoArticulo,\n        descripcion:info.descripcion,fechaSolicitud:row.fechaSolicitud||\"\",usuario:info.usuario\n      }});\n\n      // Reflejar de inmediato el estado confirmado sin esperar una segunda lectura completa.\n      setRejectedSolicitudes(prev=>{\n        const next={...(prev||{}),[key]:info};\n        try{window.localStorage.setItem(RABA03_REJECTED_STORAGE_KEY,JSON.stringify(next));}catch(_){}\n        return next;\n      });\n      setRejectModal({open:false,row:null,observacion:\"\"});\n\n      // La resincronización global es sólo verificación y jamás debe convertir\n      // un rechazo ya guardado en un falso error para el usuario.\n      loadEstadosSolicitudesCompartidos({silent:true}).catch(err=>{\n        console.warn(\"El rechazo se guardó, pero falló la verificación en segundo plano:\",err);\n      });\n    }catch(err){\n      appAlert(\"No se pudo guardar el rechazo: \"+(err?.message||err));\n    }finally{\n      setActionLoading(\"\");\n    }\n  },[rejectModal,buildSolicitudKey,postEstadoSolicitud,loadEstadosSolicitudesCompartidos]);\n'''
if old not in s:
    raise SystemExit('No se encontró confirmRejectSolicitud esperado')
s=s.replace(old,new,1)

old2='''  const restoreRejectedSolicitud=useCallback(async(row)=>{\n    if(!row)return;\n    const key=buildSolicitudKey(row);\n    setActionLoading(\"Restaurando solicitud en Google Sheets...\");\n    try{\n      await postEstadoSolicitud(\"delete_estado_solicitud\",{clave:key});\n      await loadEstadosSolicitudesCompartidos({silent:true});\n    }catch(err){appAlert(\"No se pudo restaurar la solicitud para todos: \"+(err?.message||err));}\n    finally{setActionLoading(\"\");}\n  },[buildSolicitudKey,postEstadoSolicitud,loadEstadosSolicitudesCompartidos]);\n'''
new2='''  const restoreRejectedSolicitud=useCallback(async(row)=>{\n    if(!row)return;\n    const key=buildSolicitudKey(row);\n    setActionLoading(\"Restaurando solicitud en Google Sheets...\");\n    try{\n      await postEstadoSolicitud(\"delete_estado_solicitud\",{clave:key});\n      setRejectedSolicitudes(prev=>{\n        const next={...(prev||{})};\n        delete next[key];\n        try{window.localStorage.setItem(RABA03_REJECTED_STORAGE_KEY,JSON.stringify(next));}catch(_){}\n        return next;\n      });\n      loadEstadosSolicitudesCompartidos({silent:true}).catch(err=>{\n        console.warn(\"La restauración se guardó, pero falló la verificación en segundo plano:\",err);\n      });\n    }catch(err){\n      appAlert(\"No se pudo restaurar la solicitud: \"+(err?.message||err));\n    }finally{\n      setActionLoading(\"\");\n    }\n  },[buildSolicitudKey,postEstadoSolicitud,loadEstadosSolicitudesCompartidos]);\n'''
if old2 not in s:
    raise SystemExit('No se encontró restoreRejectedSolicitud esperado')
s=s.replace(old2,new2,1)

p.write_text(s,encoding='utf-8')
print('patched')
