import{useEffect,useMemo,useState}from"react";
import{BATIDERO_LOCATION,fetchBatideroWeather,operationalRisk,weatherLabel,windDirection}from"../../services/weatherService.js";

export function useBatideroWeather(){
  const[state,setState]=useState({data:null,loading:true,error:""});
  const load=async(force=false,signal)=>{setState(current=>({...current,loading:true,error:""}));try{const data=await fetchBatideroWeather({force,signal});setState({data,loading:false,error:data.fetchError||""});}catch(error){if(!signal?.aborted)setState(current=>({...current,loading:false,error:error?.message||"Información meteorológica no disponible"}));}};
  useEffect(()=>{const controller=new globalThis.AbortController();load(false,controller.signal);return()=>controller.abort();},[]);
  return{...state,reload:()=>load(true)};
}
const n=(value,digits=0)=>Number.isFinite(Number(value))?Number(value).toLocaleString("es-AR",{maximumFractionDigits:digits}):"—";
const time=value=>value?String(value).slice(11,16):"—";
const icon=code=>code===0?"☀":code<=3?"⛅":code<=48?"🌫":code<=67?"🌧":code<=77?"❄":code<=82?"🌦":code<=86?"🌨":"⛈";

export function WeatherSummary({onOpen}){
  const{data,loading,error}=useBatideroWeather(),current=data?.current,daily=data?.daily?.[0],risk=operationalRisk(data);
  return <button type="button" onClick={onOpen} className="dm-weather-summary" style={{width:"100%",minWidth:0,padding:14,border:`1px solid ${risk.color}44`,borderRadius:14,background:"linear-gradient(135deg,rgba(12,31,45,.88),rgba(7,20,31,.76))",color:"#fff",display:"grid",gridTemplateColumns:"auto minmax(0,1fr) auto",alignItems:"center",gap:12,textAlign:"left",cursor:onOpen?"pointer":"default"}}>
    <span style={{fontSize:30}}>{icon(current?.weather_code)}</span><span style={{minWidth:0}}><strong style={{display:"block",fontSize:12,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{BATIDERO_LOCATION.name}</strong><span style={{display:"block",fontSize:10,color:"#9fb0bd",marginTop:3}}>{loading?"Actualizando…":error&&!data?"Información meteorológica no disponible":`${weatherLabel(current?.weather_code)} · Viento ${n(current?.wind_speed_10m)} km/h · ${n(current?.precipitation,1)} mm`}</span></span><span style={{textAlign:"right"}}><strong style={{display:"block",fontSize:24}}>{n(current?.temperature_2m)}°</strong><small style={{color:risk.color,fontWeight:900}}>{risk.label}</small><small style={{display:"block",color:"#9fb0bd"}}>↑{n(daily?.temperature_2m_max)}° ↓{n(daily?.temperature_2m_min)}°</small></span>
  </button>;
}

export default function WeatherModule(){
  const{data,loading,error,reload}=useBatideroWeather();
  const current=data?.current||{},today=data?.daily?.[0]||{},risk=operationalRisk(data);
  const hours=useMemo(()=>{const now=String(current.time||new Date().toISOString()).slice(0,13);return(data?.hourly||[]).filter(row=>String(row.time).slice(0,13)>=now).slice(0,24);},[data,current.time]);
  return <section className="dm-weather-module" style={{display:"grid",gap:14,minWidth:0}}>
    <style>{`@media(max-width:760px){.dm-weather-current{grid-template-columns:1fr!important}.dm-weather-metrics{grid-template-columns:repeat(2,minmax(0,1fr))!important}.dm-weather-days{grid-template-columns:repeat(2,minmax(0,1fr))!important}}`}</style>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12,flexWrap:"wrap"}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".13em",color:"#93a4b2"}}>CLIMA OPERACIONAL</div><h2 style={{fontSize:"clamp(20px,3vw,30px)",margin:"5px 0 2px"}}>{BATIDERO_LOCATION.name}</h2><div style={{fontSize:12,color:"#aab6bf"}}>{BATIDERO_LOCATION.detail}{data?.location?.elevation?` · ${n(data.location.elevation)} m s. n. m.`:""}</div></div><button type="button" onClick={reload} disabled={loading} style={buttonStyle}>{loading?"Actualizando…":"Actualizar"}</button></header>
    {error&&<div role="alert" style={{padding:10,borderRadius:10,border:"1px solid #f9731644",background:"#f9731614",color:"#fdba74",fontSize:11}}>{data?`Mostrando la última información válida. ${error}`:"Información meteorológica no disponible"}</div>}
    <div className="dm-weather-current" style={{display:"grid",gridTemplateColumns:"minmax(230px,.8fr) minmax(0,1.5fr)",gap:12}}>
      <article style={panelStyle}><div style={{display:"flex",alignItems:"center",gap:16}}><span style={{fontSize:55}}>{icon(current.weather_code)}</span><div><div style={{fontSize:42,fontWeight:900}}>{n(current.temperature_2m)}°</div><div style={{fontSize:13,color:"#cbd5df"}}>{weatherLabel(current.weather_code)}</div><div style={{fontSize:11,color:"#8fa0ad",marginTop:4}}>Sensación {n(current.apparent_temperature)}° · Máx. {n(today.temperature_2m_max)}° / Mín. {n(today.temperature_2m_min)}°</div></div></div><div style={{marginTop:15,padding:"9px 11px",borderRadius:9,background:`${risk.color}18`,border:`1px solid ${risk.color}44`,color:risk.color,fontSize:12,fontWeight:900}}>{risk.label}{risk.reasons?.length?` · ${risk.reasons.join(" · ")}`:""}</div></article>
      <div className="dm-weather-metrics" style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(100px,1fr))",gap:8}}>{[["Viento",`${n(current.wind_speed_10m)} km/h ${windDirection(current.wind_direction_10m)}`],["Ráfagas",`${n(current.wind_gusts_10m)} km/h`],["Precipitación",`${n(current.precipitation,1)} mm`],["Probabilidad",`${n(today.precipitation_probability_max)}%`],["Humedad",`${n(current.relative_humidity_2m)}%`],["Presión",`${n(current.pressure_msl)} hPa`],["Visibilidad",`${n(Number(current.visibility)/1000,1)} km`],["Nubosidad",`${n(current.cloud_cover)}%`],["UV máximo",n(today.uv_index_max,1)],["Nieve",`${n(today.snowfall_sum,1)} cm`],["Salida del sol",time(today.sunrise)],["Puesta del sol",time(today.sunset)]].map(([label,value])=><div key={label} style={{...panelStyle,padding:11}}><div style={{fontSize:9,color:"#8495a2",textTransform:"uppercase",letterSpacing:".08em"}}>{label}</div><strong style={{display:"block",fontSize:13,marginTop:5}}>{value}</strong></div>)}</div>
    </div>
    <article style={panelStyle}><h3 style={titleStyle}>PRONÓSTICO POR HORA</h3><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:5,overscrollBehaviorX:"contain"}}>{hours.map(row=><div key={row.time} style={{minWidth:94,padding:10,borderRadius:10,background:"rgba(255,255,255,.035)",textAlign:"center"}}><div style={{fontSize:10,color:"#9aabb7"}}>{time(row.time)}</div><div style={{fontSize:23,margin:"7px 0"}}>{icon(row.weather_code)}</div><strong>{n(row.temperature_2m)}°</strong><div style={{fontSize:9,color:"#9aabb7",marginTop:5}}>💨 {n(row.wind_gusts_10m)} km/h</div><div style={{fontSize:9,color:"#7dd3fc",marginTop:3}}>💧 {n(row.precipitation_probability)}%</div></div>)}</div></article>
    <article style={panelStyle}><h3 style={titleStyle}>PRONÓSTICO DE 7 DÍAS</h3><div className="dm-weather-days" style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(110px,1fr))",gap:8}}>{(data?.daily||[]).map(day=><div key={day.time} style={{padding:11,borderRadius:10,background:"rgba(255,255,255,.035)"}}><strong style={{fontSize:11,textTransform:"capitalize"}}>{new Date(`${day.time}T12:00:00`).toLocaleDateString("es-AR",{weekday:"short",day:"2-digit"})}</strong><div style={{fontSize:24,margin:"8px 0"}}>{icon(day.weather_code)}</div><div style={{fontSize:11}}>↑ {n(day.temperature_2m_max)}° · ↓ {n(day.temperature_2m_min)}°</div><div style={{fontSize:9,color:"#7dd3fc",marginTop:5}}>{n(day.precipitation_probability_max)}% · {n(day.precipitation_sum,1)} mm</div><div style={{fontSize:9,color:"#9aabb7",marginTop:3}}>Ráf. {n(day.wind_gusts_10m_max)} km/h</div></div>)}</div></article>
    <div style={{fontSize:9,color:"#71818d"}}>Pronóstico Open-Meteo · última actualización válida {data?.fetchedAt?new Date(data.fetchedAt).toLocaleString("es-AR"):"—"}. Los indicadores son apoyo operativo y no reemplazan alertas oficiales.</div>
  </section>;
}
const panelStyle={minWidth:0,padding:14,borderRadius:14,border:"1px solid rgba(255,255,255,.09)",background:"rgba(7,18,29,.7)",boxShadow:"0 14px 32px rgba(0,0,0,.2)",backdropFilter:"blur(14px)"};
const titleStyle={fontSize:11,letterSpacing:".12em",margin:"0 0 12px",color:"#dce5eb"};
const buttonStyle={padding:"9px 13px",borderRadius:9,border:"1px solid rgba(255,255,255,.14)",background:"rgba(255,255,255,.06)",color:"#fff",cursor:"pointer",fontWeight:800};
