import React,{useMemo,useState} from "react";
import {C as UI_C} from "../../components/ui/index.jsx";
import {getMonthlyCutoffRange} from "./monthlyCutoffRange.js";

const MESES=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const normDate=v=>{const s=String(v||"").trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:"";};
const clean=v=>String(v||"").trim().toUpperCase().replace(/\s*\(.*?\)/g,"");
const fmtISO=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)}`:v||"—";
const eachDay=(from,to)=>{if(!from||!to||to<from)return[];const out=[],d=new Date(`${from}T12:00:00`),end=new Date(`${to}T12:00:00`);while(d<=end){out.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`);d.setDate(d.getDate()+1);}return out;};
const machineType=(r,deps)=>r.equipo||r._tipo||deps?.getMachineType?.(r.maquina||r._internoRaw||"")||"";
const excluded=(r,code,deps)=>deps?.isRop02ControlMachineExcluded?.(code)||(()=>{const t=machineType(r,deps).toUpperCase(),c=String(code).replace(/[^A-Z0-9]/g,"");return t.includes("CAMION")||t.includes("CAMIÓN")||t.includes("CAMIONETA")||/^CTA|^CAR|^CAV|^CAT\d/.test(c)||/^AG\d|^AH\d/.test(c);})();
const matches=(value,selected,all)=>{if(selected==null||selected===all)return true;if(Array.isArray(selected))return selected.length===0||selected.includes(all)||selected.includes(value);return selected===value;};

function Multi({label,value,onChange,options,all}){const arr=Array.isArray(value)?value:[value];return <label style={{display:"flex",flexDirection:"column",gap:5,fontSize:10,fontWeight:800,color:"#8f8f96",textTransform:"uppercase"}}>{label}<select value={arr[0]||all} onChange={e=>onChange(e.target.value)} style={{minWidth:145,background:"#171719",border:"1px solid #34343a",borderRadius:7,color:"#eee",padding:"8px 10px"}}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function DateField({label,value,onChange,min,max}){return <label style={{display:"flex",flexDirection:"column",gap:5,fontSize:10,fontWeight:800,color:"#8f8f96",textTransform:"uppercase"}}>{label}<input type="date" value={value} min={min} max={max} onChange={e=>onChange(e.target.value)} style={{background:"#171719",border:"1px solid #34343a",borderRadius:7,color:"#eee",padding:"7px 9px"}}/></label>}
function Pill({active,onClick,children}){return <button onClick={onClick} style={{border:`1px solid ${active?"#ef233c":"#3b3b40"}`,background:active?"rgba(239,35,60,.12)":"#18181a",color:active?"#ef233c":"#aaa",borderRadius:7,padding:"7px 12px",fontWeight:800,cursor:"pointer"}}>{children}</button>}

export default function ViewCambiosTurnoEnhanced({deps={},rop02All=[]}){
 const C={...UI_C,...(deps.C||{})},hoy=new Date();
 const [mes,setMes]=useState(String(hoy.getMonth())),[anio,setAnio]=useState(String(hoy.getFullYear()));
 const preset=useMemo(()=>getMonthlyCutoffRange(Number(mes),Number(anio)),[mes,anio]);
 const [custom,setCustom]=useState(false),[desde,setDesde]=useState(""),[hasta,setHasta]=useState("");
 const [proyecto,setProyecto]=useState("todos"),[equipo,setEquipo]=useState("todas"),[tipo,setTipo]=useState("todos"),[tab,setTab]=useState("resumen");
 const rango=custom?{desde:desde||preset.startISO,hasta:hasta||preset.endISO}:{desde:preset.startISO,hasta:preset.endISO};
 const base=useMemo(()=>(rop02All||[]).filter(r=>{const f=normDate(r.fecha),m=clean(r.maquina||r._internoRaw);return f&&f>=rango.desde&&f<=rango.hasta&&m&&!excluded(r,m,deps);}),[rop02All,rango.desde,rango.hasta,deps]);
 const proyectos=useMemo(()=>[...new Set(base.map(r=>r.proyecto).filter(Boolean))].sort(),[base]);
 const tipos=useMemo(()=>[...new Set(base.filter(r=>matches(r.proyecto,proyecto,"todos")).map(r=>machineType(r,deps)).filter(Boolean))].sort(),[base,proyecto,deps]);
 const equipos=useMemo(()=>[...new Set(base.filter(r=>matches(r.proyecto,proyecto,"todos")&&matches(machineType(r,deps),tipo,"todos")).map(r=>clean(r.maquina||r._internoRaw)).filter(Boolean))].sort(),[base,proyecto,tipo,deps]);
 const filtered=useMemo(()=>base.filter(r=>matches(r.proyecto,proyecto,"todos")&&matches(machineType(r,deps),tipo,"todos")&&matches(clean(r.maquina||r._internoRaw),equipo,"todas")),[base,proyecto,tipo,equipo,deps]);
 const summary=useMemo(()=>{const map=new Map();filtered.forEach(r=>{const m=clean(r.maquina||r._internoRaw),key=deps.canonicalEquivalentMachineCode?.(m)||m,f=normDate(r.fecha),estado=String(r.estado||"").toUpperCase(),hs=Math.max(0,Number(r.horas)||0),turno=String(r.turno||r["Turno"]||"").toUpperCase();const x=map.get(key)||{maquina:m,equipo:machineType(r,deps),proyecto:r.proyecto||"",horas:0,td:0,tn:0,dias:new Map(),ultimaFecha:""};x.horas+=hs;if(turno.includes("TD")||turno.includes("DIA"))x.td+=hs;if(turno.includes("TN")||turno.includes("NOCHE"))x.tn+=hs;const d=x.dias.get(f)||{work:false,od:false,fs:false};if(hs>0)d.work=true;else if(estado==="OD")d.od=true;else if(estado==="FS"||estado==="EM")d.fs=true;x.dias.set(f,d);if(f>x.ultimaFecha)x.ultimaFecha=f;map.set(key,x);});return [...map.values()].map(x=>{let w=0,od=0,fs=0;x.dias.forEach(d=>{if(d.work)w++;else if(d.od)od++;else if(d.fs)fs++;});return{...x,diasTrabajados:w,diasOD:od,diasFSEM:fs,horas:+x.horas.toFixed(2),td:+x.td.toFixed(2),tn:+x.tn.toFixed(2)};}).sort((a,b)=>b.horas-a.horas);},[filtered,deps]);
 const days=useMemo(()=>eachDay(rango.desde,rango.hasta),[rango.desde,rango.hasta]);
 const daily=useMemo(()=>{const map=new Map();filtered.forEach(r=>{const m=clean(r.maquina||r._internoRaw),key=deps.canonicalEquivalentMachineCode?.(m)||m,f=normDate(r.fecha),hs=Math.max(0,Number(r.horas)||0),estado=String(r.estado||"").toUpperCase();const x=map.get(key)||{maquina:m,equipo:machineType(r,deps),proyecto:r.proyecto||"",dias:{}};const d=x.dias[f]||{hs:0,od:false,fs:false};d.hs+=hs;if(estado==="OD")d.od=true;if(estado==="FS"||estado==="EM")d.fs=true;x.dias[f]=d;map.set(key,x);});return [...map.values()].sort((a,b)=>a.maquina.localeCompare(b.maquina));},[filtered,deps]);
 const cell=d=>d?.hs>0?String(Math.round(d.hs*100)/100):d?.od?"OD":d?.fs?"FS":"—";
 const total=summary.reduce((s,r)=>s+r.horas,0);
 const exportDaily=()=>{const rows=daily.map(r=>({Equipo:r.maquina,Tipo:r.equipo,Proyecto:r.proyecto,...Object.fromEntries(days.map(d=>[fmtISO(d),cell(r.dias[d])]))}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Horas por dias");XLSX.writeFile(wb,`Horas_por_dias_${rango.desde}_${rango.hasta}.xlsx`);};
 const exportSummary=()=>{const rows=summary.map(r=>({Equipo:r.maquina,Tipo:r.equipo,Proyecto:r.proyecto,"Días trabajados":r.diasTrabajados,"Días OD":r.diasOD,"Días FS/EM":r.diasFSEM,"Hs TD":r.td,"Hs TN":r.tn,"Hs Totales":r.horas,"Último registro":r.ultimaFecha}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Resumen");XLSX.writeFile(wb,`Equipos_${rango.desde}_${rango.hasta}.xlsx`);};
 return <div className="fade-in" style={{display:"flex",flexDirection:"column",gap:14}}>
  <div style={{display:"flex",gap:8}}><Pill active={tab==="resumen"} onClick={()=>setTab("resumen")}>Equipos al fin de turno</Pill><Pill active={tab==="diario"} onClick={()=>setTab("diario")}>Horas por días</Pill></div>
  <div style={{background:"rgba(20,20,22,.94)",border:`1px solid ${C.border||"#333"}`,borderRadius:12,overflow:"hidden"}}>
   <div style={{padding:"14px 16px",borderBottom:`1px solid ${C.border||"#333"}`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>{tab==="diario"?"Horas por días":"Equipos al fin de turno"}</b><button onClick={tab==="diario"?exportDaily:exportSummary} style={{border:"1px solid #10b98166",background:"rgba(16,185,129,.12)",color:"#10b981",borderRadius:7,padding:"7px 12px",fontWeight:800,cursor:"pointer"}}>⬇ Excel</button></div>
   <div style={{padding:14,display:"flex",flexDirection:"column",gap:12}}>
    <div style={{display:"flex",flexWrap:"wrap",gap:10,alignItems:"flex-end"}}>
     <Multi label="Mes" value={mes} onChange={v=>{setMes(v);setCustom(false);setDesde("");setHasta("");}} all="0" options={MESES.map((x,i)=>({value:String(i),label:x}))}/><Multi label="Año" value={anio} onChange={v=>{setAnio(v);setCustom(false);setDesde("");setHasta("");}} all="2026" options={[...new Set([String(hoy.getFullYear()),"2026","2027","2028",...rop02All.map(r=>normDate(r.fecha).slice(0,4)).filter(Boolean)])].sort((a,b)=>+b-+a).map(x=>({value:x,label:x}))}/>
     <DateField label="Desde" value={custom?desde:preset.startISO} max={custom?hasta||undefined:undefined} onChange={v=>{setCustom(true);setDesde(v);if(hasta&&hasta<v)setHasta(v);}}/><DateField label="Hasta" value={custom?hasta:preset.endISO} min={custom?desde||undefined:undefined} onChange={v=>{setCustom(true);setHasta(v);if(desde&&desde>v)setDesde(v);}}/>
     <Multi label="Proyecto" value={proyecto} onChange={v=>{setProyecto(v);setEquipo("todas");}} all="todos" options={[{value:"todos",label:"Todos"},...proyectos.map(x=>({value:x,label:x}))]}/><Multi label="Equipo" value={equipo} onChange={setEquipo} all="todas" options={[{value:"todas",label:"Todos"},...equipos.map(x=>({value:x,label:x}))]}/><Multi label="Tipo de máquina" value={tipo} onChange={v=>{setTipo(v);setEquipo("todas");}} all="todos" options={[{value:"todos",label:"Todos"},...tipos.map(x=>({value:x,label:x}))]}/>
     <button onClick={()=>{setCustom(false);setDesde("");setHasta("");setProyecto("todos");setEquipo("todas");setTipo("todos");}} style={{marginLeft:"auto",border:"1px solid #ef233c44",background:"rgba(239,35,60,.08)",color:"#ef233c",borderRadius:7,padding:"8px 12px",cursor:"pointer"}}>× Limpiar filtros</button>
    </div>
    <div style={{fontSize:11,color:C.textSub||"#aaa"}}>Análisis sin camionetas ni camiones. Período: <b style={{color:C.text||"#fff"}}>{fmtISO(rango.desde)} al {fmtISO(rango.hasta)}</b>{custom?" · Rango personalizado":" · Corte mensual 26 al 25"}</div>
    {tab==="resumen"?<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><div style={{padding:14,borderRadius:10,background:"rgba(16,185,129,.08)",border:"1px solid #10b98133"}}><small>Equipos con horas</small><div style={{fontSize:28,fontWeight:900,color:"#10b981"}}>{summary.length}</div></div><div style={{padding:14,borderRadius:10,background:"rgba(239,35,60,.08)",border:"1px solid #ef233c33"}}><small>Horas acumuladas</small><div style={{fontSize:28,fontWeight:900,color:"#ef233c"}}>{Math.round(total*100)/100}</div></div><div style={{padding:14,borderRadius:10,background:"rgba(168,85,247,.08)",border:"1px solid #a855f733"}}><small>Criterio</small><div style={{fontSize:20,fontWeight:900,color:"#a855f7"}}>{custom?"Rango personalizado":`${MESES[+mes]} ${anio}`}</div></div></div><div style={{overflow:"auto",maxHeight:440}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Equipo","Tipo","Proyecto","Días trabajados","Días OD","Días FS/EM","Hs TD","Hs TN","Hs Totales","Último registro"].map(h=><th key={h} style={{position:"sticky",top:0,background:"#171719",padding:9,borderBottom:"1px solid #333",textAlign:"left"}}>{h}</th>)}</tr></thead><tbody>{summary.map(r=><tr key={r.maquina}>{[r.maquina,r.equipo,r.proyecto,r.diasTrabajados,r.diasOD,r.diasFSEM,r.td||"—",r.tn||"—",r.horas,fmtISO(r.ultimaFecha)].map((v,i)=><td key={i} style={{padding:8,borderBottom:"1px solid #29292d",whiteSpace:"nowrap",fontWeight:i===0||i===8?800:400,color:i===8?"#10b981":undefined}}>{v}</td>)}</tr>)}</tbody></table></div></>:
    <div style={{overflow:"auto",maxHeight:560,border:"1px solid #303035",borderRadius:8}}><table style={{borderCollapse:"separate",borderSpacing:0,fontSize:11,minWidth:"100%"}}><thead><tr><th style={{position:"sticky",left:0,top:0,zIndex:4,background:"#171719",padding:9,minWidth:110}}>Equipo</th><th style={{position:"sticky",top:0,zIndex:3,background:"#171719",padding:9,minWidth:130}}>Tipo</th><th style={{position:"sticky",top:0,zIndex:3,background:"#171719",padding:9,minWidth:110}}>Proyecto</th>{days.map(d=><th key={d} style={{position:"sticky",top:0,zIndex:3,background:"#171719",padding:7,minWidth:58,textAlign:"center",whiteSpace:"nowrap"}}>{d.slice(8,10)}/{d.slice(5,7)}</th>)}</tr></thead><tbody>{daily.map(r=><tr key={r.maquina}><td style={{position:"sticky",left:0,zIndex:2,background:"#18181a",padding:8,fontWeight:900,whiteSpace:"nowrap"}}>{r.maquina}</td><td style={{padding:8,whiteSpace:"nowrap"}}>{r.equipo}</td><td style={{padding:8,whiteSpace:"nowrap"}}>{r.proyecto}</td>{days.map(d=>{const v=cell(r.dias[d]),status=v==="OD"||v==="FS";return <td key={d} style={{padding:7,textAlign:"center",borderLeft:"1px solid #29292d",borderBottom:"1px solid #29292d",fontWeight:v!=="—"?800:400,color:v==="OD"?"#f59e0b":v==="FS"?"#ef4444":v!=="—"?"#10b981":"#666"}}>{v}</td>;})}</tr>)}</tbody></table></div>}
   </div>
  </div>
 </div>;
}
